# Generated by Django 4.0 on 2021-12-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
