# Generated by Django 4.0 on 2021-12-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_korzina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='author',
        ),
    ]
